services:
  homarr:
    image: ghcr.io/ajnart/homarr:latest
    container_name: homarr
    restart: unless-stopped
    ports:
      - "7575:7575"
    volumes:
      - homarr-configs:/app/data/configs
      - homarr-icons:/app/public/icons
      - homarr-data:/data
    environment:
      - TZ=Asia/Jakarta

volumes:
  homarr-configs:
  homarr-icons:
  homarr-data:
